--------------------------------------------------------
DROP SEQUENCE "SYSTEM"."BOOK_S";
DROP SEQUENCE "SYSTEM"."AUTHOR_S";
DROP SEQUENCE "SYSTEM"."REVIEW_S";

DROP TABLE "SYSTEM"."BOOK";
DROP TABLE "SYSTEM"."AUTHOR";
DROP TABLE "SYSTEM"."BOOK_AUTHOR";
DROP TABLE "SYSTEM"."REVIEW";
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOOK_S
--------------------------------------------------------

CREATE SEQUENCE  "SYSTEM"."BOOK_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_S
--------------------------------------------------------

CREATE SEQUENCE  "SYSTEM"."REVIEW_S"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUTHOR_S
--------------------------------------------------------

CREATE SEQUENCE  "SYSTEM"."AUTHOR_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

CREATE TABLE "SYSTEM"."BOOK"
(	"ID" NUMBER NOT NULL ENABLE,
   "NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE,
   "PUBLISHED_DATE" DATE NOT NULL ENABLE,
   "ISBN" VARCHAR2(20 BYTE) NOT NULL ENABLE,
   "PUBLISHER" VARCHAR2(40 BYTE) NOT NULL ENABLE,
   "BOOK_CREATE" DATE NOT NULL ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK_AUTHOR
--------------------------------------------------------

CREATE TABLE "SYSTEM"."BOOK_AUTHOR"
(	"BOOK_ID" NUMBER ,
   "AUTHOR_ID" NUMBER
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

CREATE TABLE "SYSTEM"."REVIEW"
(	"ID" NUMBER NOT NULL ENABLE,
   "COMMENTER_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE,
   "COMMENT_BODY" CLOB,
   "COMMENT_RATING" NUMBER(*,0) NOT NULL ENABLE,
   "COMMENT_CREATE" DATE NOT NULL ENABLE,
   "BOOK_ID" NUMBER NOT NULL ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"
LOB ("COMMENT_BODY") STORE AS BASICFILE (
TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
NOCACHE LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

CREATE TABLE "SYSTEM"."AUTHOR"
(	"ID" NUMBER NOT NULL ENABLE,
   "FIRST_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
   "SECOND_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
   "AUTHOR_CREATE" DATE NOT NULL ENABLE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

Insert into SYSTEM.BOOK (ID,NAME,PUBLISHED_DATE,ISBN,PUBLISHER,BOOK_CREATE) values ('34','book name',to_date('09.11.2015','DD.MM.RRRR'),'ISBN2015-ORM6','publisher name',to_date('09.11.2015','DD.MM.RRRR'));
Insert into SYSTEM.BOOK (ID,NAME,PUBLISHED_DATE,ISBN,PUBLISHER,BOOK_CREATE) values ('36','book name',to_date('09.11.2015','DD.MM.RRRR'),'ISBN2015-ORM7','publisher name',to_date('09.11.2015','DD.MM.RRRR'));
Insert into SYSTEM.BOOK (ID,NAME,PUBLISHED_DATE,ISBN,PUBLISHER,BOOK_CREATE) values ('38','book name',to_date('09.11.2015','DD.MM.RRRR'),'ISBN2015-ORM9','publisher name',to_date('09.11.2015','DD.MM.RRRR'));
Insert into SYSTEM.BOOK (ID,NAME,PUBLISHED_DATE,ISBN,PUBLISHER,BOOK_CREATE) values ('32','book name',to_date('09.11.2015','DD.MM.RRRR'),'ISBN2015-ORM4','publisher name',to_date('09.11.2015','DD.MM.RRRR'));
Insert into SYSTEM.BOOK (ID,NAME,PUBLISHED_DATE,ISBN,PUBLISHER,BOOK_CREATE) values ('33','book name',to_date('09.11.2015','DD.MM.RRRR'),'ISBN2015-ORM5','publisher name',to_date('09.11.2015','DD.MM.RRRR'));

Insert into SYSTEM.BOOK_AUTHOR (BOOK_ID,AUTHOR_ID) values ('36','1');
Insert into SYSTEM.BOOK_AUTHOR (BOOK_ID,AUTHOR_ID) values ('38','1');

Insert into SYSTEM.REVIEW (ID,COMMENTER_NAME,COMMENT_RATING,COMMENT_CREATE,BOOK_ID) values ('48','commenter name','5',to_date('09.11.2015','DD.MM.RRRR'),'34');
Insert into SYSTEM.REVIEW (ID,COMMENTER_NAME,COMMENT_RATING,COMMENT_CREATE,BOOK_ID) values ('46','commenter name','5',to_date('09.11.2015','DD.MM.RRRR'),'32');
Insert into SYSTEM.REVIEW (ID,COMMENTER_NAME,COMMENT_RATING,COMMENT_CREATE,BOOK_ID) values ('50','commenter name','5',to_date('09.11.2015','DD.MM.RRRR'),'36');
Insert into SYSTEM.REVIEW (ID,COMMENTER_NAME,COMMENT_RATING,COMMENT_CREATE,BOOK_ID) values ('52','commenter name','5',to_date('09.11.2015','DD.MM.RRRR'),'38');
Insert into SYSTEM.REVIEW (ID,COMMENTER_NAME,COMMENT_RATING,COMMENT_CREATE,BOOK_ID) values ('47','commenter name','5',to_date('09.11.2015','DD.MM.RRRR'),'33');

Insert into SYSTEM.AUTHOR (ID,FIRST_NAME,SECOND_NAME,AUTHOR_CREATE) values ('1','first name','second name',to_date('09.11.2015','DD.MM.RRRR'));
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."BOOK" ADD CONSTRAINT "BOOK_UK1" UNIQUE ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
--------------------------------------------------------
--  Constraints for Table BOOK_AUTHOR
--------------------------------------------------------

--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table BOOK_AUTHOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOK_AUTHOR" ADD CONSTRAINT "BOOK_AUTHOR_FK1" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SYSTEM"."BOOK" ("ID") DISABLE;
 
  ALTER TABLE "SYSTEM"."BOOK_AUTHOR" ADD CONSTRAINT "BOOK_AUTHOR_FK2" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SYSTEM"."AUTHOR" ("ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REVIEW" ADD CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SYSTEM"."BOOK" ("ID") ENABLE;
